//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopAppMorison
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user187_dbEntities : DbContext
    {
        public user187_dbEntities()
            : base("name=user187_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PO_Customer> PO_Customer { get; set; }
        public virtual DbSet<PO_Equipment> PO_Equipment { get; set; }
        public virtual DbSet<PO_ListOfIncludedChannelsAndServices> PO_ListOfIncludedChannelsAndServices { get; set; }
        public virtual DbSet<PO_NameAdditionalServices> PO_NameAdditionalServices { get; set; }
        public virtual DbSet<PO_NameEquipmentType> PO_NameEquipmentType { get; set; }
        public virtual DbSet<PO_Orders> PO_Orders { get; set; }
        public virtual DbSet<PO_Repair> PO_Repair { get; set; }
        public virtual DbSet<PO_ServicePackages> PO_ServicePackages { get; set; }
        public virtual DbSet<PO_Status> PO_Status { get; set; }
    }
}
