//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopAppMorison
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PO_Customer()
        {
            this.PO_Orders = new HashSet<PO_Orders>();
        }
    
        public int id_customer { get; set; }
        public string FirstNameCustomer { get; set; }
        public string LastNameCustomer { get; set; }
        public string MiddleNameCustomer { get; set; }
        public string PhoneNumberCustomer { get; set; }
        public string EmailCustomer { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_Orders> PO_Orders { get; set; }
    }
}
