//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopAppMorison
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PO_Equipment()
        {
            this.PO_Orders = new HashSet<PO_Orders>();
            this.PO_Repair = new HashSet<PO_Repair>();
        }
    
        public int id_equipment { get; set; }
        public int EquipmentType { get; set; }
        public int SerialNumber { get; set; }
        public string AvailableEquipmentInStock { get; set; }
        public string InstallationDate { get; set; }
        public Nullable<System.DateTime> LastRepairDate { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual PO_NameEquipmentType PO_NameEquipmentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_Orders> PO_Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_Repair> PO_Repair { get; set; }

        public int? id_customer { get; set; }
        public virtual PO_Customer PO_Customer { get; set; }
    }
}
