//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopAppMorison
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_Orders
    {
        public int id_order { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int id_customer { get; set; }
        public int id_package { get; set; }
        public int id_equipment { get; set; }
        public int OrderTotal { get; set; }
        public string Adress { get; set; }
    
        public virtual PO_Customer PO_Customer { get; set; }
        public virtual PO_Equipment PO_Equipment { get; set; }
        public virtual PO_ServicePackages PO_ServicePackages { get; set; }
    }
}
