//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopAppMorison
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_ServicePackages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PO_ServicePackages()
        {
            this.PO_Orders = new HashSet<PO_Orders>();
        }
    
        public int id_package { get; set; }
        public string PackageName { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public string Duration { get; set; }
        public int ListOfIncludedChannelsAndServices { get; set; }
    
        public virtual PO_ListOfIncludedChannelsAndServices PO_ListOfIncludedChannelsAndServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_Orders> PO_Orders { get; set; }
    }
}
